/* Generated by Opal 0.11.4 */
(function(Opal) {
  var TMP_5, self = Opal.top, $nesting = [], nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass, $send = Opal.send, $hash2 = Opal.hash2;

  Opal.add_stubs(['$include', '$render', '$H1', '$on', '$BUTTON', '$alert', '$ready?', '$[]', '$create_element']);
  
  (function($base, $super, $parent_nesting) {
    function $HelloWorld(){};
    var self = $HelloWorld = $klass($base, $super, 'HelloWorld', $HelloWorld);

    var def = self.$$proto, $nesting = [self].concat($parent_nesting), TMP_HelloWorld_1;

    
    self.$include(Opal.const_get_qualified(Opal.const_get_relative($nesting, 'Hyperstack'), 'Component'));
    return $send(self, 'render', [Opal.const_get_relative($nesting, 'DIV')], (TMP_HelloWorld_1 = function(){var self = TMP_HelloWorld_1.$$s || this, TMP_2, TMP_3, TMP_4;

    
      $send(self, 'H1', [], (TMP_2 = function(){var self = TMP_2.$$s || this;

      return "Hello World from precompiled component"}, TMP_2.$$s = self, TMP_2.$$arity = 0, TMP_2));
      return $send($send(self, 'BUTTON', [], (TMP_3 = function(){var self = TMP_3.$$s || this;

      return "Click me"}, TMP_3.$$s = self, TMP_3.$$arity = 0, TMP_3)), 'on', ["click"], (TMP_4 = function(){var self = TMP_4.$$s || this;

      return self.$alert("hello")}, TMP_4.$$s = self, TMP_4.$$arity = 0, TMP_4));}, TMP_HelloWorld_1.$$s = self, TMP_HelloWorld_1.$$arity = 0, TMP_HelloWorld_1));
  })($nesting[0], null, $nesting);
  return $send(Opal.const_get_relative($nesting, 'Document'), 'ready?', [], (TMP_5 = function(){var self = TMP_5.$$s || this, mount_point = nil;

  
    self.$include(Opal.const_get_qualified(Opal.const_get_relative($nesting, 'Hyperstack'), 'Component'));
    mount_point = Opal.const_get_relative($nesting, 'Element')['$[]']("#site");
    return Opal.const_get_relative($nesting, 'ReactAPI').$render(Opal.const_get_relative($nesting, 'ReactAPI').$create_element(Opal.const_get_relative($nesting, 'HelloWorld'), $hash2([], {})), mount_point);}, TMP_5.$$s = self, TMP_5.$$arity = 0, TMP_5));
})(Opal);
